#!/bin/bash

ACCOUNT_ID=${aws_account_id}
REGION=${aws_region}

yum update -y
yum install -y docker
systemctl start docker
systemctl enable docker

# Optional, doesn't really help with scripting
usermod -aG docker ec2-user

# Install Docker Compose
mkdir -p /usr/libexec/docker/cli-plugins
curl -SL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" -o /usr/libexec/docker/cli-plugins/docker-compose
chmod +x /usr/libexec/docker/cli-plugins/docker-compose

# ECR login
aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"

# Write compose file
cat <<EOF > /home/ec2-user/compose.yml
services:
  client:
    image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/client:latest
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    image: $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/server:latest
    container_name: server
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
      HOST: 0.0.0.0
      PORT: 8080
EOF

sudo systemctl restart docker
until docker info >/dev/null 2>&1; do sleep 1; done
cd /home/ec2-user && sudo docker compose up -d