#!/bin/bash

echo "Preparing for clean docker compose up..."

(
  cd ..
  docker compose down
  cd client
  echo "Cleaning Next.js cache..."
  rm -rf .next out node_modules/.cache
  cd ..
  echo "Building..."
  docker compose build --no-cache
  echo "Starting containers..."
  docker compose up -d
  docker ps
)

echo "Done."
